Added handler-executor interface
php-task/php-task pull request #38
Opened 2017-08-09 07:49 UTC by wachterjohannes

2017-08-11 13:05 UTC, chirimoya requested changes

2017-08-11 13:05 UTC, chirimoya commented on composer.json
> +        "symfony/process": "^2.6 || ^3.0",
remove

2017-08-11 13:05 UTC, chirimoya commented on src/Task/Runner/InlineExecutor.php
> +class InlineExecutor implements ExecutorInterface
`InsideProcessExecutor`

2017-08-14 05:54 UTC, wachterjohannes commented
@chirimoya fixed

2017-08-21 13:59 UTC, merged